packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'tools/*'
  - 'test'
  - 'templates/blank'
  # exclude packages that are inside test directories
  # - '!**/test/**'

# Allow all build scripts
neverBuiltDependencies: []
